### ISSUE TITLE
How to use datazoomer?

### ISSUE THREAD

**Issue by labeebmaqsood13** [dsilabs/datazoomer#10]
Hi Guys,

Do you have any detailed documentation for datazoomer? I have seen the site but is not very helpful.

Thanks.

@hlainchb @brettgoss @sean-hayes @TyneBloomfield

**Comment by hlainchb** [comment]
We do have internal documentation but unfortunately we're not currently able to release it.  We're working on the Python 3 ready successor to DataZoomer which is just called [Zoom](https://github.com/dsilabs/zoom), and we plan to provide proper documentation for it.
